/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:211023:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:211023:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("P.O.O.P.");
  button1 = new GButton(this, 500, 820, 70, 60);
  button1.setText("+");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  label1 = new GLabel(this, 20, 10, 170, 40);
  label1.setText("My label");
  label1.setLocalColorScheme(GCScheme.SCHEME_15);
  label1.setOpaque(false);
  label2 = new GLabel(this, 220, 10, 160, 40);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("My label");
  label2.setLocalColorScheme(GCScheme.SCHEME_15);
  label2.setOpaque(false);
  label3 = new GLabel(this, 450, 10, 130, 40);
  label3.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  label3.setText("My label");
  label3.setLocalColorScheme(GCScheme.SCHEME_15);
  label3.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
